### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [skrixx68/Dota2-Overlay-2.0#4]

**Comment by aeristhy** [comment]
Open Dota2 first then you can open the Overlay after.

**Comment by KhalifaAdiwijaya** [comment]
Now the issue is when i open dota 2 and start running the overlay, the overlay covers my dota 2 tab so i can't see the game, if i press the "delete" button the app will stop. And the second issue is that the overlay always says "waiting", I have the latest offsets file but I don't know where to put the offsets file to fix the issue. How to solve these two issues? I really appreciate your help.

![IMG_20211004_182647](https://user-images.githubusercontent.com/72883457/135846088-e3be40fd-896d-45b4-9417-4db4d00c0050.jpg)
